baseURL = 'https://centerforopenneuroscience.org'
languageCode = 'en-us'
title = 'Center for Open Neuroscience'
relativeURLs = true

[taxonomies]
  people_category = 'people_categories'
  person = 'people'
  project_type = 'project_types'
  project = 'projects'
  publication = 'publications'

[params]
  description = 'Center for Open Neuroscience'
  author = 'CON'
